<a href="https://colab.research.google.com/github/farid22022/Machine_Learning_From_Zero_to_Hero/blob/main/Complete_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of Numpy Arrays
1. Alows several Mathematical Operation
2. Faster operations

In [2]:
import numpy as np

List vs Numpy - time Taken

In [ ]:
from time import process_time

Time taken  by a list

In [5]:
python_list = [i for i in range(1000000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.05826724499999969


In [7]:
np_array = np.array([i for i in range(1000000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0010448719999978096


Numpy Array

In [8]:
#List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [9]:
#numpy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [10]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [11]:
a.shape()

TypeError: 'tuple' object is not callable

In [12]:
a.shape

(5,)

In [13]:
b=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
b.shape

(2, 5)

dtype

In [16]:
c= np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=float)
print(c)
c.shape

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


(2, 5)

1. np.zeros((r,c))
2. np.ones((r,c))
3. np.full((r,c),x)


In [18]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
z = np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Create an Identity Matrix

In [25]:
a = np.eye(5)
print(a)
print(np.eye(5,3))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


Create a numpy array with random values

1. random.random((r,c))
2. random.randint(a,b,(r,c))

In [26]:
b = np.random.random((5,5))
print(b)

[[0.65908393 0.24512343 0.38975452 0.12754713 0.1496193 ]
 [0.33661715 0.34046845 0.36003472 0.0136339  0.00819437]
 [0.52619171 0.15290864 0.80690886 0.31802637 0.2720966 ]
 [0.16149888 0.76370518 0.28610818 0.04621487 0.2698341 ]
 [0.03647228 0.5869035  0.50198465 0.1646056  0.16832573]]


Random integer values array within a specific range

In [28]:
c = np.random.randint(10,100,(5,5,5))
print(c)

[[[35 90 15 59 57]
  [63 25 77 73 10]
  [38 56 59 68 15]
  [92 51 44 95 55]
  [52 43 25 70 60]]

 [[48 12 50 29 70]
  [87 37 18 71 58]
  [72 49 85 19 47]
  [41 13 57 13 42]
  [92 62 51 50 45]]

 [[16 93 80 85 57]
  [25 24 31 31 46]
  [44 88 85 71 69]
  [87 73 27 77 34]
  [81 85 86 40 27]]

 [[68 87 37 10 16]
  [19 91 37 94 28]
  [16 54 26 91 93]
  [10 27 98 58 48]
  [62 55 73 79 11]]

 [[92 70 67 21 32]
  [22 87 13 20 85]
  [74 90 18 50 97]
  [44 53 28 87 88]
  [88 60 26 85 78]]]


An array of evenly spaced values
1. np.linspace(starting_point, end_point, number_of_portion)

In [34]:
d = np.linspace(10,30,5)
print(d)
e = np.linspace(1,10,2)
print(np.linspace(1,100,12))
print(e)

[10. 15. 20. 25. 30.]
[  1.  10.  19.  28.  37.  46.  55.  64.  73.  82.  91. 100.]
[ 1. 10.]
